const str = require('../dist/index')
console.log('-------------------------------------------------------')
const data = str.split('Hello Word', 3)
console.log('text:', data)
console.log('-------------------------------------------------------')
